import { ReactNode } from "react";
import Navigation from "@/app/components/Navigation";
import Logo from "@/app/components/Logo";

export const metadata = {
  title: "The Wild Oasis",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <header>
          <Logo />
          <Navigation />
        </header>
        <main>{children}</main>
        <footer>Copyright by The Wild Oasis. All rights reserved.</footer>
      </body>
    </html>
  );
}
